database_jkm_wyx_yzh/database_jkm_wyx_yzh/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import university, account, user, major, post
from django.conf import settings
from django.conf.urls.static import static
from app.utils.upload import upload_file

urlpatterns = [
    # 管理员后台
    path('admin/', admin.site.urls),
    # 登陆
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # 大学
    path('university/list/', university.university_list),
    path('university/<int:uid>/major/list/', university.university_major_list),

    # 用户
    path('user/register/', user.user_register),
    path('user/profile/', user.user_profile),
    path('user/notification/center/', user.user_notification_center),
    path('user/edit/', user.user_edit),
    path('user/edit/password/', user.user_edit_password),
    path('user/post/list/', user.user_post_list),
    path('user/post/<int:post_id>/delete/', user.user_post_delete),
    path('user/draft/list/', user.user_draft_list),
    path('user/draft/<int:draft_id>/delete/', user.user_draft_delete),

    # 专业
    path('major/list/', major.major_list),
    path('major/<str:mid>/university/list/', major.major_university_list),
    path('major/<int:uid>/<str:mid>/detail/', major.major_detail_info),
    path('major/<int:uid>/<str:mid>/detail/analyze/', major.major_detail_analyze),
    path('major/<int:uid>/<str:mid>/detail/analyze/bar/', major.major_detail_analyze_bar),
    path('major/<int:uid>/<str:mid>/detail/exam/', major.major_detail_exam),
    path('major/<int:uid>/<str:mid>/detail/post/', major.major_detail_post),

    # 帖子
    path('post/list/', post.post_list),
    path('post/<int:pid>/detail/', post.post_detail),
    path('post/search/', post.post_search),
    path('post/create/', post.post_create),
    path('post/create_from/draft/<int:draft_id>/', post.post_create_from_draft),
    path('post/<int:pid>/detail/like/', post.toggle_like),
    path('post/save/tags/', post.save_tags),

    # 上传文件
    path('', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # 配置静态文件url


# 配置用户上传文件url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "一研为定管理后台"
admin.site.index_title = "一研为定管理后台"
admin.site.site_title = "一研为定管理员登陆了"

database_jkm_wyx_yzh/app/models.py
from django.db import models
from django.utils.functional import cached_property  # 缓存装饰器
from django.template.loader import render_to_string  # 渲染模版
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
major_in_buaa = (
    (1, '材料科学与工程学院'),
    (2, '电子信息工程学院'),
    (3, '自动化科学与电气工程学院'),
    (4, '能源与动力工程学院'),
    (5, '航空科学与工程学院'),
    (6, '计算机学院'),
    (7, '机械工程及自动化学院'),
    (8, '经济管理学院'),
    (9, '数学科学学院'),
    (10, '生物与医学工程学院'),
    (11, '人文社会科学学院'),
    (12, '外国语学院'),
    (13, '交通科学与工程学院'),
    (14, '可靠性与系统工程学院'),
    (15, '宇航学院'),
    (16, '飞行学院'),
    (17, '仪器科学与光电工程学院'),
    (18, '北京学院'),
    (19, '物理学院'),
    (20, '法学院'),
    (21, '软件学院'),
    (23, '高等理工学院'),
    (24, '中法工程师学院/国际通用工程师学院'),
    (25, '国际学院'),
    (26, '新媒体艺术与设计学院'),
    (27, '化学学院'),
    (28, '马克思主义学院'),
    (29, '人文与社会科学高等研究院'),
    (30, '空间与环境学院'),
    (39, '网络空间安全学院'),
    (41, '继续教育学院'),
    (42, '人工智能研究院'),
    (44, '研究生院'),
    (48, '前沿科学技术创新研究院'),
    (49, '集成电路科学与工程学院'),
)

Major_type = (
    (1, '哲学'),
    (2, '经济学'),
    (3, '法学'),
    (4, '教育学'),
    (5, '文学'),
    (6, '历史学'),
    (7, '理学'),
    (8, '工学'),
    (9, '农学'),
    (10, '医学'),
    (11, '军事学'),
    (12, '管理学'),
    (13, '艺术学'),
    (14, '交叉学科'),
)


# 用户表
class User(models.Model):
    user_name = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    major_choices = major_in_buaa
    major = models.SmallIntegerField(verbose_name='本科专业', choices=major_choices)
    introduction = models.CharField(verbose_name='简介', max_length=100, blank=True, default="")
    age = models.IntegerField(verbose_name='年龄', default=0)
    gender_choices = ((1, '男'), (0, '女'))
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices, default=1)
    image = models.ImageField(verbose_name='头像', upload_to='media/images/', default='/static/img/default.jpg',
                              blank=True, null=True)

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user_name


# 学校表
class University(models.Model):
    image = models.ImageField(verbose_name='校徽', upload_to='static/img/', default='static/img/buaa.png')
    university_id = models.IntegerField(verbose_name='院校代码', primary_key=True)
    name = models.CharField(verbose_name='学校名字', max_length=32)
    location = models.CharField(verbose_name='所在地区', max_length=16)
    info = models.CharField(verbose_name='联系方式', max_length=32)
    university_tag_choices = ((0, '普通高校'), (1, '211'), (2, '985, 211'))
    university_tag = models.SmallIntegerField(verbose_name='学校标签', choices=university_tag_choices, default=0)

    class Meta:
        verbose_name = '大学'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 专业（别的大学）
class Major(models.Model):
    major_id = models.CharField(verbose_name='专业代码', primary_key=True, max_length=16)
    major_name = models.CharField(verbose_name='专业名称', max_length=32)
    major_type = models.SmallIntegerField(verbose_name='专业类别', choices=Major_type)

    class Meta:
        verbose_name = '专业'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.major_name


# 专业学校联系表
class MajorUniversity(models.Model):
    major = models.ForeignKey(to=Major, verbose_name='专业', on_delete=models.CASCADE)
    university_id = models.ForeignKey(to='University', to_field='university_id', verbose_name='大学',
                                      on_delete=models.CASCADE)
    school = models.CharField(verbose_name='学院名称', max_length=64)

    class Meta:
        verbose_name = '专业-学校'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.major.major_name + '-' + self.university_id.name


# 录取信息表
class AdmitInfo(models.Model):
    total_score = models.DecimalField(verbose_name='总分', max_digits=6, decimal_places=2)
    score1 = models.IntegerField(verbose_name='初试分数')
    score2 = models.DecimalField(verbose_name='复试分数', max_digits=6, decimal_places=2)
    year = models.IntegerField(verbose_name='年份')
    major_id = models.ForeignKey(to='Major', to_field='major_id', on_delete=models.CASCADE)
    university_id = models.ForeignKey(to='University', to_field='university_id', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '录取信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.major_id) + '-' + str(self.university_id) + '-录取信息'


class ExamInfo(models.Model):
    """
    改设计文档
    """
    major_id = models.ForeignKey(to='Major', to_field='major_id', on_delete=models.CASCADE)
    university_id = models.ForeignKey(to='University', to_field='university_id', on_delete=models.CASCADE)
    professional_exam1 = models.CharField(verbose_name='专业课1', max_length=16)
    professional_exam2 = models.CharField(verbose_name='专业课2', max_length=16)
    english_exam = models.CharField(verbose_name='英语', max_length=16)
    politic_exam = models.CharField(verbose_name='政治', max_length=16)

    class Meta:
        verbose_name = '考试科目'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.major_id) + '-' + str(self.university_id) + '-考试科目'


# 帖子表
class Post(models.Model):
    title = models.CharField(verbose_name='帖子标题', max_length=16)
    content = RichTextUploadingField(verbose_name='帖子正文', max_length=5000)
    create_time = models.DateTimeField(verbose_name='帖子创建时间', auto_now_add=True)
    author = models.ForeignKey(to='User', to_field='id', verbose_name='帖子作者', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '帖子'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Draft(models.Model):
    title = models.CharField(verbose_name='草稿标题', max_length=16)
    content = RichTextUploadingField(verbose_name='草稿正文', max_length=5000, blank=True, null=True)
    create_time = models.DateTimeField(verbose_name='帖子创建时间', auto_now=True)
    author = models.ForeignKey(to='User', to_field='id', verbose_name='帖子作者', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '草稿'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title + '（草稿）'


# 通知实体表
class CommentNotification(models.Model):
    """
    改设计文档
    """
    post_id = models.ForeignKey(to='Post', to_field='id', on_delete=models.CASCADE)
    comment_id = models.ForeignKey(to='Comment', to_field='id', on_delete=models.CASCADE)
    message = models.CharField(verbose_name='通知内容', max_length=32)
    time = models.DateTimeField(verbose_name='通知创建时间', auto_now=True)
    is_new = models.BooleanField(verbose_name='是否是新的通知', default=True)

    class Meta:
        verbose_name = '评论通知'
        verbose_name_plural = verbose_name


# 通知-用户联系表
class CommentNotify(models.Model):
    """
    改设计文档
    """
    notification = models.ForeignKey(to=CommentNotification, on_delete=models.CASCADE)
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论通知-用户'
        verbose_name_plural = verbose_name


class LikeNotification(models.Model):
    """
    改设计文档
    """
    post_id = models.ForeignKey(to=Post, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='点赞的用户')
    message = models.CharField(verbose_name='通知内容', max_length=32)
    time = models.DateTimeField(verbose_name='通知创建时间', auto_now=True)
    is_new = models.BooleanField(verbose_name='是否是新的通知', default=True)

    class Meta:
        verbose_name = '点赞通知'
        verbose_name_plural = verbose_name


class LikeNotify(models.Model):
    """
    改设计文档
    """
    notification = models.ForeignKey(to=LikeNotification, on_delete=models.CASCADE)
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = '点赞通知-用户'
        verbose_name_plural = verbose_name


# 评论表
class Comment(models.Model):
    post_id = models.ForeignKey(to='Post', to_field='id', on_delete=models.CASCADE)
    # father_id = models.IntegerField(verbose_name='父级评论id')
    # like_count = models.IntegerField(verbose_name='点赞数')
    author = models.ForeignKey(to='User', to_field='id', verbose_name='帖子作者', on_delete=models.CASCADE)
    create_time = models.DateTimeField(verbose_name='评论创建时间', auto_now=True)
    content = RichTextField(verbose_name='评论内容', max_length=200)


# 点赞关系表
class Like(models.Model):
    """
    改设计文档
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    """
    改设计文档
    """
    name = models.CharField(max_length=10, verbose_name='文章标签')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    edit_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = '帖子标签'

    def __str__(self):
        return self.name


# 帖子-关键词联系表
class TagPost(models.Model):
    tag = models.ForeignKey(to=Tag, on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)

    class Meta:
        verbose_name = '帖子-关键词'
        verbose_name_plural = verbose_name


class SideBar(models.Model):
    # 侧边栏的模型数据

    STATUS = (
        (1, '隐藏'),
        (2, '展示')
    )

    DISPLAY_TYPE = (
        (1, '搜索'),
        (2, '最新文章'),
        (3, '最热文章'),
        (4, '文章归档'),
        (5, 'HTML')
    )

    title = models.CharField(max_length=50, verbose_name="模块名称")  # 模块名称
    display_type = models.PositiveIntegerField(default=1, choices=DISPLAY_TYPE,
                                               verbose_name="展示类型")  # 侧边栏  搜索框/最新文章/热门文章/HTML自定义等
    content = models.CharField(max_length=500, blank=True, default='', verbose_name="内容",

database_jkm_wyx_yzh/app/views/user.py
from django.shortcuts import render, redirect
from app import models

from app.utils.pagination import Pagination
from app.utils.model_form import UserModelForm, EditPwdModelForm


def user_register(request):
    """ 注册用户 """
    title = '注册用户'
    if request.method == 'GET':
        form = UserModelForm()
        return render(request, 'user/user_register.html', {'title': title, 'form': form})

    # 用户Post提交数据，并进行校验
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        # 数据合法，保存到数据库
        form.save()
        user = models.User.objects.filter(**form.cleaned_data).first()
        if request.FILES:
            user.image = request.FILES['image']
            user.save()
        # 网站生成随机字符串；写到用户浏览器的cookie中；再写入到session中；
        request.session['info'] = {'id': user.id, 'name': user.user_name}
        # session保存一天
        request.session.set_expiry(60 * 60 * 24)
        return redirect('/university/list/')
    else:
        # 校验失败，显示错误信息
        return render(request, 'change.html', {'title': title, 'form': form})


def user_profile(request):
    nid = request.session['info'].get('id')
    user = models.User.objects.filter(id=nid).first()
    return render(request, 'user/user_profile.html', {'user': user})


def user_edit(request):
    """编辑用户"""
    uid = request.session['info'].get('id')
    user = models.User.objects.filter(id=uid).first()
    if request.method == 'GET':
        # 根据id去数据库获取要编辑的那一行数据
        context = {
            'user': user,
        }
        return render(request, 'user/user_edit.html', context=context)
    data = {
        'user_name': request.POST.get('user_name'),
        'password': user.password,
        'age': request.POST.get('age'),
        'major': request.POST.get('major'),
        'introduction': request.POST.get('introduction'),
        'gender': request.POST.get('gender'),
    }
    form = UserModelForm(data=data, instance=user)
    if form.is_valid():
        form.save()
        if request.FILES:
            user.image = request.FILES['image']
        user.save()
        return redirect('/user/profile/')
    else:
        return render(request, 'user/user_edit.html', {'form': form})


def user_edit_password(request):
    uid = request.session['info'].get('id')
    user = models.User.objects.filter(id=uid).first()
    context = {}
    if request.method == 'GET':
        return render(request, 'user/user_edit_password.html', context=context)
    form = EditPwdModelForm(data=request.POST, instance=user)
    if form.is_valid():
        form.save()
        return redirect('/user/profile/')
    context['form'] = form
    return render(request, 'user/user_edit_password.html', context=context)


def user_notification_center(request):
    uid = request.session['info'].get('id')
    user = models.User.objects.filter(id=uid).first()
    comment_notification_id_list = models.CommentNotify.objects.filter(owner=user)
    comment_notifications = models.CommentNotification.objects.filter(
        id__in=[i.notification.id for i in comment_notification_id_list]).all().order_by('-time')
    like_notification_id_list = models.LikeNotify.objects.filter(owner=user)
    like_notifications = models.LikeNotification.objects.filter(
        id__in=[i.notification.id for i in like_notification_id_list]).all().order_by('-time')

    # 更新消息的状态
    comment_notifications.filter(is_new=True).update(is_new=False)
    like_notifications.filter(is_new=True).update(is_new=False)
    context = {
        'comment_notifications': comment_notifications,
        'like_notifications': like_notifications,
    }
    return render(request, 'user/user_profile_notification_center.html', context=context)


def user_post_list(request):
    uid = request.session['info'].get('id')
    user = models.User.objects.filter(id=uid).first()
    posts = models.Post.objects.filter(author=user).all().order_by('-create_time')
    context = {
        'posts': posts
    }
    return render(request, 'user/user_post_list.html', context=context)


def user_post_delete(request, post_id):
    models.Post.objects.get(id=post_id).delete()
    return redirect('/user/post/list/')


def user_draft_list(request):
    uid = request.session['info'].get('id')
    user = models.User.objects.filter(id=uid).first()
    drafts = models.Draft.objects.filter(author=user).all().order_by('-create_time')
    context = {
        'drafts': drafts,
    }
    return render(request, 'user/user_draft_list.html', context=context)


def user_draft_delete(request, draft_id):
    models.Draft.objects.get(id=draft_id).delete()
    return redirect('/user/draft/list/')

database_jkm_wyx_yzh/app/templates/user/user_draft_list.html
{% extends 'user/user_profile.html' %}

{% block title %}
    <li class="is-active"><a>我的草稿</a></li>
{% endblock %}

{% block profile_content %}
    {% if drafts %}
        {% for draft in drafts %}
            <div class="box">
                <div style="display: inline-block; width: 800px">
                    <h1 class="is-size-5 has-text-weight-bold">
                        <a href="/post/create_from/draft/{{ draft.id }}">{{ draft.title }}</a>
                    </h1>
                    <span class="is-size-7 has-text-grey-light pt-1 pb-1">
                        <span>发布日期：{{ draft.create_time }}</span>
                    </span>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="box">
            当前暂无草稿！
        </div>
    {% endif %}
{% endblock %}

database_jkm_wyx_yzh/app/templates/user/user_edit.html
{% extends 'user/user_profile.html' %}
{% load static %}

{% block title %}
    <li class="is-active"><a>编辑用户</a></li>
{% endblock %}

{% block profile_content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="field">
            <label class="label">用户名</label>
            <div class="control has-icons-left has-icons-right">
                <input class="input" type="text" name="user_name" value="{{ user.user_name }}">
                <span class="icon is-small is-left">
                <i class="fas fa-user"></i>
            </span>
                <span class="icon is-small is-right">
                <i class="fas fa-check"></i>
            </span>
            </div>
        </div>

        <div class="field">
            <label class="label">年龄</label>
            <div class="control has-icons-left has-icons-right">
                <input class="input" type="text" name="age" value="{{ user.age }}">
                <span class="icon is-small is-left">
                <i class="fas fa-user"></i>
            </span>
                <span class="icon is-small is-right">
                <i class="fas fa-check"></i>
            </span>
            </div>
        </div>

        <div class="field">
            <label class="label">本科专业</label>
            <div class="control">
                <div class="select">
                    <select name="major">
                        <option value="{{ user.major }}">{{ user.get_major_display }}</option>
                        {% for item in user.major_choices %}
                            <option value="{{ item.0 }}">{{ item.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label class="label">简介</label>
            <div class="control">
                <textarea class="textarea" name="introduction">{{ user.introduction }}</textarea>
            </div>
        </div>

        <div class="field">
            <label class="label">性别</label>
            <div class="control">
                <div class="select" name="gender">
                    <select name="gender" id="">
                        <option value="{{ user.gender }}">{{ user.get_gender_display }}</option>
                        {% for item in user.gender_choices %}
                            <option value="{{ item.0 }}">{{ item.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="file has-name">
            <label class="file-label">
                <input class="file-input" id="avatarInput" type="file" name="image">
                <span class="file-cta">
                <span class="file-icon">
                    <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                    上传头像
                </span>
            </span>
                <figure class="image" style="width: 50px; height: 50px; margin-left: 10px">
                    <img class="is-rounded" id="avatarPreview" src="
                        {% if user.image %}
                            {{ user.image.url }}
                        {% else %}
                            /static/img/default.jpg
                        {% endif %}" alt="">
                </figure>

            </label>
        </div>

        <div class="field is-grouped" style="margin-top: 5px">
            <div class="control">
                <button type="submit" class="button is-link">Submit</button>
            </div>
            <div class="control">
                <a class="button is-link is-light" href="/user/profile/">Cancel</a>
            </div>
        </div>
    </form>

{% endblock %}

{% block js %}
    <script>
        const avatarInput = document.getElementById('avatarInput');
        const avatarPreview = document.getElementById('avatarPreview');

        avatarInput.addEventListener('change', function () {
            const file = this.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    avatarPreview.src = e.target.result;
                }
                reader.readAsDataURL(file);
            }
        });
    </script>
{% endblock %}

database_jkm_wyx_yzh/app/templates/user/user_profile.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-2">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">个人中心</p>
                            <a href="" class="card-header-icon" aria-label="more options">
                                <span class="icon">
                                    <i class="fas fa-angle-down" aria-hidden="true"></i>
                                </span>
                            </a>
                        </header>
                        <div class="card-content menu">
                            <ul class="content menu-list">
                                <li><a href="/user/profile/">个人信息</a></li>
                                <li><a href="/user/edit/password/">修改密码</a></li>
                            </ul>
                        </div>

                    </div>
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">内容管理</p>
                            <a href="#" class="card-header-icon" aria-label="more options">
                                    <span class="icon">
                                        <i class="fas fa-angle-down" aria-hidden="true"></i>
                                    </span>
                            </a>
                        </header>
                        <div class="card-content menu">
                            <ul class="content menu-list">
                                <li>
                                    <a href="/user/notification/center/">
                                        我的消息
                                        {% if count_new_all %}
                                            <span class="badge">
                                                {{ count_new_all }}
                                            </span>
                                        {% endif %}
                                    </a>
                                </li>
                                <li><a href="/user/post/list/">已发布</a></li>
                                <li><a href="/user/draft/list/">草稿箱</a></li>
{#                                <li><a href="">评论管理</a></li>#}
{#                                <li><a href="">数据分析</a></li>#}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="column is-10">
                    <div class="box is-radiusless is-shadowless">
                        <div class="tabs">
                            <ul>
                                {% block title %}
                                    <li class="is-active"><a>账号信息</a></li>
                                {% endblock %}
                            </ul>
                        </div>
                        {% block profile_content %}
                            <div class="columns is-mobile"
                                 style="border-bottom: #ededed solid 1px; padding-bottom: 1rem">
                                <div class="column is-narrow">
                                    <figure class="image is-96x96">
                                        {% if user.image %}
                                            <img class="is-rounded"
                                                 src="{{ user.image.url }}" alt="">
                                        {% else %}
                                            <img class="is-rounded" src=" {% static 'img/default.jpg' %}" alt="">
                                        {% endif %}
                                    </figure>
                                </div>
                                <div class="column is-narrow">
                                    <div style="padding-top: 1.5rem;">
                                        <h1 class="title is-size-4">{{ user.user_name }}</h1>
                                    </div>
                                </div>
                                <div class="column is-narrow-mobile">
                                    <a class=" button is-light is-pulled-right"
                                       href="/user/edit/" style="margin-top: 1.8rem">修改信息</a>
                                </div>
                            </div>

                            <div class="columns" style="padding: 1rem 0;">
                                <div class="column is-2">
                                    <p>个人信息</p>
                                </div>
                                <div class="column">
                                    <div class="columns is-mobile" style="border-bottom: #dddddd solid 1px">
                                        <div class="column is-2">
                                            <span class="has-text-grey-light">用户名</span>
                                        </div>
                                        <div class="column is-narrow">
                                            <span class=" has-text-black-ter">{{ user.user_name }}</span>
                                        </div>
                                    </div>
                                    <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                        <div class="column is-2">
                                            <span class=" has-text-grey-light">学院</span>
                                        </div>
                                        <div class="column is-narrow">
                                            <span class=" has-text-black-ter">{{ user.get_major_display }}</span>
                                        </div>
                                    </div>
                                    <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                        <div class="column is-2">
                                            <span class=" has-text-grey-light">年龄</span>
                                        </div>
                                        <div class="column is-narrow">
                                            <span class=" has-text-black-ter">{{ user.age }}</span>
                                        </div>
                                    </div>
                                    <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                        <div class="column is-2">
                                            <span class=" has-text-grey-light">性别</span>
                                        </div>
                                        <div class="column is-narrow">
                                            <span class=" has-text-black-ter">{{ user.get_gender_display }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="columns" style="padding:1rem 0; ">
                                <div class="column is-2">
                                    <p>个人简介</p>
                                </div>
                                <div class="column">
                                    <div class="content">
                                        {% if user.introduction %}
                                            {{ user.introduction }}
                                        {% else %}
                                            暂未设置
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

database_jkm_wyx_yzh/app/templates/user/user_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 50px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h1 class="title">用户注册</h1>
    <form action="/user/register/" method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                <label class="label">{{ field.label }}</label>
                {{ field }}
                <span style="color: red">{{ field.errors.0 }}</span>
            </div>
        {% endfor %}

        <button type="submit" class="button is-primary is-right">提 交</button>
    </form>
</div>
</body>
</html>